frontend_homepage:
    path:     /
    defaults: { _controller: "SiteMainBundle:Frontend/Main:index" }

frontend_work:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/project.yml"
    prefix: /project

frontend_feedback:
    path:     /feedback/{idModuleHeader}/{local}
    defaults: { _controller: "SiteMainBundle:Frontend/Main:feedback", local: false }